In [1]:
pass

In [14]:
with open("input-2.txt") as f:
    data = f.read()

In [15]:
lines = data.split("\n")[:-1]

In [16]:
lines[0]

'29x13x26'

In [21]:
dims = np.array([[int(i) for i in j.split("x")] for j in lines])

In [19]:
import numpy as np

In [22]:
dims.drop(1,axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

In [23]:
dims

array([[29, 13, 26],
       [11, 11, 14],
       [27,  2,  5],
       ...,
       [ 3,  2, 22],
       [14,  3,  5],
       [10,  9,  8]])

In [28]:
dims[:,:2].prod(axis=1)

array([377, 121,  54,  60, 285, 754, 184, 136, 560, 276, 187, 437,  50,
        15, 350, 230, 551, 170, 780, 112,  35, 184,  40,  72,  60,  84,
       230, 841,  21, 220, 120, 260,  24,  32, 486,  72, 306, 350, 450,
       306, 644, 180,  98, 667, 120, 132,  15,  70, 672, 391,  60, 184,
        90, 414,  17, 299,  36, 484, 220, 812, 462, 112, 360,  56,  90,
        12, 450, 112,  12, 144, 560, 672,  72, 414,  88, 450,  84,  66,
        12,  18, 187, 600, 189, 104,  58, 456, 529, 728,  72, 750, 551,
        48, 725, 342, 294, 247, 190,  36, 108, 600, 108,  45, 510, 342,
        99, 224,  33, 476, 432, 132, 114, 112, 616, 377, 144, 812, 180,
       209, 728, 391,  25,  17, 459, 364, 182, 319, 638,  78, 414, 175,
       162, 231, 308, 325, 551, 464, 210, 175,  45,  15, 216, 138, 484,
       120, 650, 190, 600, 150, 170, 420, 136, 126,  15, 408, 280, 594,
       252, 207, 336, 126,  27, 130,  60, 460, 176, 812, 208, 189, 182,
       299, 133, 207, 189, 189, 580, 299, 475, 132, 420, 126, 624, 609,
       754,  96,  24,  42,  14, 132, 143, 675,  88, 286,  90, 567, 240,
       132,  99, 299, 117, 660, 667, 475, 203, 342, 725, 600,   9, 198,
       168, 399, 325, 350,  56, 105,  18,  12, 285, 510, 460, 546, 754,
         8,  88,  39, 162,  15,  84, 308, 108,  22, 195, 266, 560,  80,
       182, 342,   7, 460, 702, 165, 210,  58, 588,  54, 442, 364, 140,
       216,  32, 120, 696,  25,  28, 288, 696, 208,  98, 165, 180, 102,
        12, 240, 783,  48,  84, 696, 396,  56, 140, 171, 340,  58, 475,
       252, 783, 147,  40, 208, 364, 135,  36,  81, 510, 330,  24, 174,
       480, 720, 380,  18, 312, 285, 336, 299, 400,  72, 336, 360, 171,
       184,  44, 261,  48, 300,  33,  30,  91,  14, 234, 720, 476,  80,
       165, 120, 576, 650,  52, 325, 264, 140, 216, 208,  28, 276, 624,
       702, 442, 408, 130, 115,  90, 504, 140, 420, 100, 624,  35,  13,
         5,  70,  88, 260, 510, 638, 312, 459, 702, 130, 242, 208, 456,
         7, 162, 112, 224,  20, 475, 225, 140, 288, 567,  25,   7,  32,
       195,  75, 580,  36, 130, 675, 330, 133, 162, 336, 609, 368, 551,
        25, 405, 208, 551,  96,  54, 325,  45, 200,  81, 483,  44, 216,
       161, 780, 435, 432,  36, 270, 180,  20, 208, 546, 702, 270, 323,
       375, 260, 110, 130, 120,  72, 350, 224, 504,  16, 400, 459, 240,
       312,  51, 135, 216,  58, 552,  30, 108, 182, 750, 144,  84,  66,
       240,  78, 168, 126,  42, 224, 242,  80, 456, 192,  36,  36,  90,
         5, 475, 600, 195,  81, 280, 624,  50, 260, 228, 108,  20, 702,
       416,  63,  52, 154, 676,  10, 323, 756,  18, 570, 690,  45,  28,
       378,  88, 114, 234, 160, 264, 364, 350,  84, 170, 270, 230, 350,
       264, 750, 286,  14, 220, 198, 304, 264, 187,  24, 260, 168, 270,
        45,  77, 220, 546, 260, 216,  24, 216, 391,  84,  40, 391,  26,
         4,  30, 286, 525, 420, 216, 272, 336, 288, 348, 360, 264,  36,
        96, 209, 150,  20, 176, 286, 304,  96,  26,  50,  96,  42, 442,
       414, 308,   4, 145,  45,  35, 300, 165, 168, 406, 252, 350, 364,
       104,  30,  12, 288,  48, 210, 360, 242, 480, 306, 182,  56,  84,
       870,  24, 180, 330,  76, 180, 616, 780,  72,  10, 725, 153, 336,
       294, 240, 156, 192,  40,  18, 152, 126, 378,  26, 270, 405, 198,
        29, 252,  40, 644,   1, 161, 270, 144, 360, 330, 754,  45,   2,
        42,  18, 450, 340, 280, 336, 187,  36,  64, 322, 231,  65, 116,
       840,  72,  45, 117, 420,  63, 187, 624, 336, 459,  42,  99,   9,
       104, 400, 377, 330,  70, 135, 391, 126, 360,  72, 288, 242,  28,
        45, 200,  16, 690, 150, 238, 176,  77, 442,  46, 364, 216, 506,
       168, 160, 323,  58,  52, 464, 104, 240, 368, 224, 168, 260, 114,
       510,  28,  26, 126,  52,  48, 360,   6, 621, 660, 575, 368,  75,
        30, 319, 600, 112,  60, 324, 160,   3,  22,  48, 319,  30,  10,
       168, 330, 180, 351,  84, 522,  48,  87, 300,  35,  14, 225, 168,
       476, 234, 390,  21, 192,  24, 105, 323, 336,  20, 189, 442, 180,
       115,  16, 208, 378, 754, 384, 182, 154,  18, 108, 702,  23, 725,
        90, 160,  50, 750, 154, 728, 116, 231, 180, 550,  22,  46, 621,
        26,  54,  11,  48, 320, 360,  75,  10,  48,  16, 108, 336, 702,
       144, 288, 400, 232,  84,   8,  52,  60, 180,  30, 192, 418, 136,
       400,   7,  10, 529, 168,  50, 270, 648, 196,   4, 432, 400, 672,
        90, 135, 598, 408, 550, 522, 500, 264, 140, 140, 182,  90, 416,
        40, 810, 234, 128, 162, 252, 169, 162, 270, 418, 140, 725,  18,
        88, 108, 720,  27, 135,  58,  52, 198, 400, 616, 130,  33, 336,
       468, 540,  77, 150,  54, 810, 392,  28, 168, 247, 572, 210,  34,
       494, 456, 322, 567, 450, 609, 690,   4,  75,  42, 140,  21,  50,
       348, 364,  78, 580, 336, 120, 240,  96,  56, 600, 390, 340, 216,
        19, 216, 352, 494, 143, 264, 156, 493,  84, 280, 208, 325,  90,
       392, 870,  51,  72, 672,  96, 500, 289, 114, 150, 184, 203, 162,
        50,  54, 288,  75, 754, 308, 261, 360, 234,   5, 594, 203,   3,
        56, 399, 364, 272,  50, 126, 210,  64, 168,  81, 484,  20, 228,
       435, 308, 522,   7,  24, 529, 204, 260, 176,   8, 418,  46, 297,
       390, 189, 162, 462,  84, 483,  42,  45, 841, 675,  24,  16, 551,
       288,  54, 280, 168, 522, 209, 165, 126, 280, 468, 675, 120,  60,
       280, 180, 242, 352, 375,  50, 112, 456,  12,  56, 286, 144, 182,
         6,  27,   4,  78,  48, 204,  76,  90, 102, 570,  22, 390, 506,
       476,  85,  77, 546, 420,  30,  72, 153, 540,  70, 378,  28, 112,
       120, 551, 253, 128,  51, 130, 420,  69, 702,   6,  42,  90])

In [41]:
sides = np.stack([dims[:,:2],dims[:,::2], dims[:,-2:]])

In [42]:
sides.shape

(3, 1000, 2)

In [43]:
side_area = sides.prod(axis=2)
side_area

array([[377, 121,  54, ...,   6,  42,  90],
       [754, 154, 135, ...,  66,  70,  80],
       [338, 154,  10, ...,  44,  15,  72]])

In [44]:
side_area.min(axis=0).sum() + 2 * side_area.sum()

1586300

In [45]:
side_per = 2 * sides.sum(axis=2)
side_per

array([[ 84,  44,  58, ...,  10,  34,  38],
       [110,  50,  64, ...,  50,  38,  36],
       [ 78,  50,  14, ...,  48,  16,  34]])

In [47]:
side_per.min(axis=0).sum() + dims.prod(axis=1).sum()

3737498